"""Phase 8A-5 full schema

Revision ID: a94bcc78431f
Revises: 0001_baseline
Create Date: 2026-05-27 20:13:11.695010

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94bcc78431f'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjacency_patterns',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pattern_shape', sa.String(length=40), nullable=False),
    sa.Column('cells', sa.JSON(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjacency_patterns_role'), 'adjacency_patterns', ['role'], unique=False)
    op.create_table('behaviors',
    sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('family', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('walkable', sa.Boolean(), nullable=True),
    sa.Column('has_encounter', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family', 'name', name='uq_behaviors_family_name')
    )
    op.create_table('embeddings_lookup',
    sa.Column('uuid_str', sa.String(length=36), nullable=False),
    sa.Column('collection', sa.String(length=64), nullable=False),
    sa.Column('entity_kind', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid_str')
    )
    op.create_index('idx_emb_lookup_collection_model', 'embeddings_lookup', ['collection', 'model', 'model_version'], unique=False)
    op.create_index('idx_emb_lookup_entity', 'embeddings_lookup', ['entity_kind', 'entity_id'], unique=False)
    op.create_table('tag_taxonomy',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('axis', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_leaf', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tag_taxonomy.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_taxonomy_axis'), 'tag_taxonomy', ['axis'], unique=False)
    op.create_index(op.f('ix_tag_taxonomy_parent_id'), 'tag_taxonomy', ['parent_id'], unique=False)
    op.create_index(op.f('ix_tag_taxonomy_slug'), 'tag_taxonomy', ['slug'], unique=True)
    op.create_table('tilesets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid_str', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('family', sa.String(length=16), nullable=False),
    sa.Column('is_secondary', sa.Boolean(), nullable=False),
    sa.Column('is_compressed', sa.Boolean(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_commit', sa.String(length=64), nullable=True),
    sa.Column('license_spdx', sa.String(length=64), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ingested_by', sa.String(length=120), nullable=True),
    sa.Column('content_hash', sa.LargeBinary(), nullable=False),
    sa.Column('raw_bytes_size', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid_str')
    )
    op.create_index(op.f('ix_tilesets_content_hash'), 'tilesets', ['content_hash'], unique=False)
    op.create_index(op.f('ix_tilesets_project_id'), 'tilesets', ['project_id'], unique=False)
    op.create_index(op.f('ix_tilesets_slug'), 'tilesets', ['slug'], unique=True)
    op.create_table('metatiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tileset_id', sa.BigInteger(), nullable=False),
    sa.Column('metatile_index', sa.SmallInteger(), nullable=False),
    sa.Column('behavior_id', sa.SmallInteger(), nullable=False),
    sa.Column('terrain_type', sa.SmallInteger(), nullable=False),
    sa.Column('encounter_type', sa.SmallInteger(), nullable=False),
    sa.Column('layer_type', sa.SmallInteger(), nullable=False),
    sa.Column('attr_raw', sa.LargeBinary(), nullable=False),
    sa.Column('composition', sa.JSON(), nullable=False),
    sa.Column('rendered_hash', sa.LargeBinary(), nullable=False),
    sa.Column('phash', sa.BigInteger(), nullable=False),
    sa.Column('is_walkable', sa.Boolean(), nullable=False),
    sa.Column('is_surfable', sa.Boolean(), nullable=False),
    sa.Column('is_encounter_grass', sa.Boolean(), nullable=False),
    sa.Column('feature_vec_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tileset_id'], ['tilesets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tileset_id', 'metatile_index', name='uq_metatiles_tileset_index')
    )
    op.create_index(op.f('ix_metatiles_behavior_id'), 'metatiles', ['behavior_id'], unique=False)
    op.create_index(op.f('ix_metatiles_is_walkable'), 'metatiles', ['is_walkable'], unique=False)
    op.create_index(op.f('ix_metatiles_phash'), 'metatiles', ['phash'], unique=False)
    op.create_index(op.f('ix_metatiles_rendered_hash'), 'metatiles', ['rendered_hash'], unique=False)
    op.create_index(op.f('ix_metatiles_tileset_id'), 'metatiles', ['tileset_id'], unique=False)
    op.create_table('palettes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tileset_id', sa.BigInteger(), nullable=False),
    sa.Column('palette_index', sa.SmallInteger(), nullable=False),
    sa.Column('colors_bgr555', sa.LargeBinary(), nullable=False),
    sa.Column('colors_rgba', sa.LargeBinary(), nullable=True),
    sa.Column('median_cut_5', sa.JSON(), nullable=False),
    sa.Column('dominant_hue', sa.SmallInteger(), nullable=True),
    sa.Column('luminance_avg', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tileset_id'], ['tilesets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tileset_id', 'palette_index', name='uq_palettes_tileset_index')
    )
    op.create_index(op.f('ix_palettes_tileset_id'), 'palettes', ['tileset_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid_str', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('width', sa.SmallInteger(), nullable=False),
    sa.Column('height', sa.SmallInteger(), nullable=False),
    sa.Column('cells', sa.JSON(), nullable=False),
    sa.Column('anchor_x', sa.SmallInteger(), nullable=False),
    sa.Column('anchor_y', sa.SmallInteger(), nullable=False),
    sa.Column('origin_tileset_id', sa.BigInteger(), nullable=True),
    sa.Column('required_tags', sa.JSON(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['origin_tileset_id'], ['tilesets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'scope', 'project_id', name='uq_templates_slug_scope_project'),
    sa.UniqueConstraint('uuid_str')
    )
    op.create_index(op.f('ix_templates_role'), 'templates', ['role'], unique=False)
    op.create_table('tiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tileset_id', sa.BigInteger(), nullable=False),
    sa.Column('tile_index', sa.SmallInteger(), nullable=False),
    sa.Column('pixel_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('content_hash', sa.LargeBinary(), nullable=False),
    sa.Column('palette_neutral_hash', sa.LargeBinary(), nullable=False),
    sa.Column('phash', sa.BigInteger(), nullable=False),
    sa.Column('is_blank', sa.Boolean(), nullable=False),
    sa.Column('is_horizontal_symm', sa.Boolean(), nullable=False),
    sa.Column('is_vertical_symm', sa.Boolean(), nullable=False),
    sa.Column('feature_vec_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tileset_id'], ['tilesets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tileset_id', 'tile_index', name='uq_tiles_tileset_index')
    )
    op.create_index(op.f('ix_tiles_content_hash'), 'tiles', ['content_hash'], unique=False)
    op.create_index(op.f('ix_tiles_palette_neutral_hash'), 'tiles', ['palette_neutral_hash'], unique=False)
    op.create_index(op.f('ix_tiles_phash'), 'tiles', ['phash'], unique=False)
    op.create_index(op.f('ix_tiles_tileset_id'), 'tiles', ['tileset_id'], unique=False)
    op.create_table('adjacency_observations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('metatile_a', sa.BigInteger(), nullable=False),
    sa.Column('metatile_b', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('source_corpus', sa.String(length=120), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['metatile_a'], ['metatiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metatile_b'], ['metatiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metatile_a', 'metatile_b', 'direction', 'source_corpus', name='uq_adj_obs_pair_dir_corpus')
    )
    op.create_index(op.f('ix_adjacency_observations_metatile_a'), 'adjacency_observations', ['metatile_a'], unique=False)
    op.create_index(op.f('ix_adjacency_observations_metatile_b'), 'adjacency_observations', ['metatile_b'], unique=False)
    op.create_table('adjacency_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('metatile_a', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('legal_neighbors', sa.JSON(), nullable=False),
    sa.Column('hard_legal_set', sa.JSON(), nullable=False),
    sa.Column('total_observations', sa.Integer(), nullable=False),
    sa.Column('entropy', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['metatile_a'], ['metatiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metatile_a', 'direction', 'scope', 'project_id', name='uq_adj_rules_metatile_dir_scope')
    )
    op.create_index(op.f('ix_adjacency_rules_metatile_a'), 'adjacency_rules', ['metatile_a'], unique=False)
    op.create_table('metatile_tags',
    sa.Column('metatile_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['metatile_id'], ['metatiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag_taxonomy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metatile_id', 'tag_id')
    )
    op.create_index(op.f('ix_metatile_tags_tag_id'), 'metatile_tags', ['tag_id'], unique=False)
    op.create_table('template_usage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=False),
    sa.Column('map_corpus', sa.String(length=200), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_usage_map_corpus'), 'template_usage', ['map_corpus'], unique=False)
    op.create_index(op.f('ix_template_usage_template_id'), 'template_usage', ['template_id'], unique=False)
    op.create_table('tile_tags',
    sa.Column('tile_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag_taxonomy.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tile_id'], ['tiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tile_id', 'tag_id')
    )
    op.create_index(op.f('ix_tile_tags_tag_id'), 'tile_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tile_tags_tag_id'), table_name='tile_tags')
    op.drop_table('tile_tags')
    op.drop_index(op.f('ix_template_usage_template_id'), table_name='template_usage')
    op.drop_index(op.f('ix_template_usage_map_corpus'), table_name='template_usage')
    op.drop_table('template_usage')
    op.drop_index(op.f('ix_metatile_tags_tag_id'), table_name='metatile_tags')
    op.drop_table('metatile_tags')
    op.drop_index(op.f('ix_adjacency_rules_metatile_a'), table_name='adjacency_rules')
    op.drop_table('adjacency_rules')
    op.drop_index(op.f('ix_adjacency_observations_metatile_b'), table_name='adjacency_observations')
    op.drop_index(op.f('ix_adjacency_observations_metatile_a'), table_name='adjacency_observations')
    op.drop_table('adjacency_observations')
    op.drop_index(op.f('ix_tiles_tileset_id'), table_name='tiles')
    op.drop_index(op.f('ix_tiles_phash'), table_name='tiles')
    op.drop_index(op.f('ix_tiles_palette_neutral_hash'), table_name='tiles')
    op.drop_index(op.f('ix_tiles_content_hash'), table_name='tiles')
    op.drop_table('tiles')
    op.drop_index(op.f('ix_templates_role'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_palettes_tileset_id'), table_name='palettes')
    op.drop_table('palettes')
    op.drop_index(op.f('ix_metatiles_tileset_id'), table_name='metatiles')
    op.drop_index(op.f('ix_metatiles_rendered_hash'), table_name='metatiles')
    op.drop_index(op.f('ix_metatiles_phash'), table_name='metatiles')
    op.drop_index(op.f('ix_metatiles_is_walkable'), table_name='metatiles')
    op.drop_index(op.f('ix_metatiles_behavior_id'), table_name='metatiles')
    op.drop_table('metatiles')
    op.drop_index(op.f('ix_tilesets_slug'), table_name='tilesets')
    op.drop_index(op.f('ix_tilesets_project_id'), table_name='tilesets')
    op.drop_index(op.f('ix_tilesets_content_hash'), table_name='tilesets')
    op.drop_table('tilesets')
    op.drop_index(op.f('ix_tag_taxonomy_slug'), table_name='tag_taxonomy')
    op.drop_index(op.f('ix_tag_taxonomy_parent_id'), table_name='tag_taxonomy')
    op.drop_index(op.f('ix_tag_taxonomy_axis'), table_name='tag_taxonomy')
    op.drop_table('tag_taxonomy')
    op.drop_index('idx_emb_lookup_entity', table_name='embeddings_lookup')
    op.drop_index('idx_emb_lookup_collection_model', table_name='embeddings_lookup')
    op.drop_table('embeddings_lookup')
    op.drop_table('behaviors')
    op.drop_index(op.f('ix_adjacency_patterns_role'), table_name='adjacency_patterns')
    op.drop_table('adjacency_patterns')
    # ### end Alembic commands ###
