import { promises as fsp } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';

export class SharePackageError extends Error {
  constructor(
    public readonly code:
      | 'patch_not_found'
      | 'base_rom_not_found'
      | 'output_dir_escapes_project_root'
      | 'mutation_failed'
      | 'invalid_meta',
    message: string,
  ) {
    super(message);
    this.name = 'SharePackageError';
  }
}

export interface ShareMeta {
  readonly modName: string;
  readonly version: string;
  readonly author: string;
  readonly description: string;
}

export interface MaterializeSharePackageOptions {
  readonly projectRoot: string;
  /** Project-relative path to the .ips patch to ship. */
  readonly patchPath: string;
  /** Absolute or project-relative path to the base ROM (for hash; not copied). */
  readonly baseRomPath: string;
  readonly meta: ShareMeta;
  /** Project-relative path to the directory where the package materializes. */
  readonly outputDir: string;
}

export interface SharePackageFile {
  readonly relativePath: string;
  readonly sizeBytes: number;
}

export interface MaterializeSharePackageResult {
  readonly outputDir: string;
  readonly files: ReadonlyArray<SharePackageFile>;
  readonly totalSize: number;
  readonly baseRomSha256: string;
}

function resolveAbsolute(projectRoot: string, p: string): string {
  if (path.isAbsolute(p)) return p;
  return path.resolve(projectRoot, p);
}

function validateMeta(meta: ShareMeta): void {
  for (const [k, v] of Object.entries(meta) as Array<[keyof ShareMeta, string]>) {
    if (typeof v !== 'string') {
      throw new SharePackageError('invalid_meta', `meta.${k} must be a string`);
    }
  }
  if (meta.modName.trim().length === 0) {
    throw new SharePackageError('invalid_meta', 'meta.modName is required');
  }
}

function renderReadme(
  meta: ShareMeta,
  baseRomSha256: string,
  patchFileName: string,
  /** Modernize-and-Ship slice 8 - when the patch is BPS the editor
   *  appends a CFRU attribution + non-commercial clause section, so
   *  recipients see Skeli789's stated license terms. */
  includeCfruAttribution = false,
): string {
  const lines: string[] = [];
  lines.push(`# ${meta.modName}`);
  lines.push('');
  if (meta.version) lines.push(`**Version:** ${meta.version}`);
  if (meta.author) lines.push(`**Author:** ${meta.author}`);
  if (meta.version || meta.author) lines.push('');
  lines.push('## Overview');
  lines.push('');
  if (meta.description.trim().length > 0) {
    lines.push(meta.description.trim());
  } else {
    lines.push('_(no description provided)_');
  }
  lines.push('');
  lines.push('## How to apply');
  lines.push('');
  lines.push('1. Obtain a clean base ROM matching the SHA-256 below.');
  lines.push(`2. Apply \`${patchFileName}\` using a patcher such as \`flips\`:`);
  lines.push('');
  lines.push('```');
  lines.push(`flips --apply ${patchFileName} base.gba patched.gba`);
  lines.push('```');
  lines.push('');
  lines.push('## Base ROM hash');
  lines.push('');
  lines.push('Validate your base ROM matches before applying:');
  lines.push('');
  lines.push('```');
  lines.push(`SHA-256: ${baseRomSha256}`);
  lines.push('```');
  lines.push('');
  if (includeCfruAttribution) {
    lines.push('## What this patch is built on');
    lines.push('');
    lines.push('This hack uses Complete Fire Red Upgrade (CFRU) by Skeli789. CFRU adds modern battle features to Pokémon FireRed. Read more at https://github.com/Skeli789/Complete-Fire-Red-Upgrade.');
    lines.push('');
    lines.push("By the terms of CFRU's license, this hack - and any hack built on CFRU - is non-commercial. The patch author must not sell it, accept donations for it, or otherwise profit from it.");
    lines.push('');
  }
  lines.push('---');
  lines.push('_Generated by the editor - patch + README + base-ROM hash, no project internals shipped._');
  return lines.join('\n');
}

async function atomicWriteFile(absPath: string, data: Buffer | string): Promise<void> {
  const tmp = absPath + '.tmp';
  try {
    await fsp.writeFile(tmp, data);
    await fsp.rename(tmp, absPath);
  } catch (e) {
    try {
      await fsp.unlink(tmp);
    } catch {
      /* ignore */
    }
    throw new SharePackageError(
      'mutation_failed',
      `Atomic write failed for '${absPath}': ${e instanceof Error ? e.message : String(e)}`,
    );
  }
}

export async function materializeSharePackage(
  options: MaterializeSharePackageOptions,
): Promise<MaterializeSharePackageResult> {
  const { projectRoot, patchPath, baseRomPath, meta, outputDir } = options;
  validateMeta(meta);

  // Output dir must stay inside the project root.
  const outputAbs = path.resolve(projectRoot, outputDir);
  const projectAbs = path.resolve(projectRoot);
  if (outputAbs !== projectAbs && !outputAbs.startsWith(projectAbs + path.sep)) {
    throw new SharePackageError(
      'output_dir_escapes_project_root',
      `Output dir '${outputDir}' resolves outside the project root`,
    );
  }

  // Patch lives inside the project tree.
  const patchAbs = path.resolve(projectRoot, patchPath);
  let patchBytes: Buffer;
  try {
    patchBytes = await fsp.readFile(patchAbs);
  } catch {
    throw new SharePackageError('patch_not_found', `Patch file not found: ${patchAbs}`);
  }

  // Base ROM hash - read + SHA-256.
  const baseAbs = resolveAbsolute(projectRoot, baseRomPath);
  let baseBytes: Buffer;
  try {
    baseBytes = await fsp.readFile(baseAbs);
  } catch {
    throw new SharePackageError('base_rom_not_found', `Base ROM not found: ${baseAbs}`);
  }
  const baseRomSha256 = createHash('sha256').update(baseBytes).digest('hex');

  // Ensure outputDir exists.
  try {
    await fsp.mkdir(outputAbs, { recursive: true });
  } catch (e) {
    throw new SharePackageError(
      'mutation_failed',
      `Could not create output directory: ${e instanceof Error ? e.message : String(e)}`,
    );
  }

  const patchFileName = path.basename(patchPath);
  // Modernize-and-Ship slice 8 - if the patch is BPS (i.e. ends in
  // `.bps`), surface the CFRU attribution + non-commercial clause in
  // the README. The file extension is the load-bearing signal here:
  // a CFRU-modernized export uses BPS to handle the expanded ROM's
  // upper-half edits, vanilla-base hacks ship IPS and don't need the
  // CFRU section.
  const includeCfruAttribution = patchFileName.toLowerCase().endsWith('.bps');
  const readme = renderReadme(meta, baseRomSha256, patchFileName, includeCfruAttribution);

  // Copy patch + write README atomically.
  const patchOutAbs = path.join(outputAbs, patchFileName);
  await atomicWriteFile(patchOutAbs, patchBytes);

  const readmeOutAbs = path.join(outputAbs, 'README.md');
  await atomicWriteFile(readmeOutAbs, readme);

  const files: SharePackageFile[] = [
    { relativePath: patchFileName, sizeBytes: patchBytes.length },
    { relativePath: 'README.md', sizeBytes: Buffer.byteLength(readme, 'utf8') },
  ];

  return {
    outputDir,
    files,
    totalSize: files.reduce((a, f) => a + f.sizeBytes, 0),
    baseRomSha256,
  };
}
