/**
 * Write a decomp-native map: `data/maps/<Name>/map.json`, a stub `scripts.inc`
 * (defining the `<Name>_MapScripts` label the generated header.inc points at),
 * registration in `data/maps/map_groups.json`, and the `.include` line in the
 * git-tracked `data/event_scripts.s` (the one manual wiring step - without it
 * `<Name>_MapScripts` is an undefined symbol → link error).
 *
 * NOT edited (all auto-generated by tools/mapjson from the JSON): header.inc,
 * events.inc, connections.inc, groups.inc, include/constants/map_groups.h,
 * include/constants/map_event_ids.h.
 */
import path from 'node:path';
import {
  writeFileAtomic,
  readJsonFile,
  stringifyDecompJson,
  fileExists,
  appendLineIfMissing,
} from './decomp-write-util.js';

export interface MapConnection {
  readonly map: string;
  readonly offset: number;
  readonly direction: 'up' | 'down' | 'left' | 'right' | 'dive' | 'emerge';
}
export interface MapWarp {
  readonly x: number;
  readonly y: number;
  readonly elevation: number;
  readonly dest_map: string;
  readonly dest_warp_id: string;
}
export interface MapObjectEvent {
  readonly local_id?: string;
  readonly type?: string;
  readonly graphics_id: string;
  readonly x: number;
  readonly y: number;
  readonly elevation: number;
  readonly movement_type: string;
  readonly movement_range_x: number;
  readonly movement_range_y: number;
  readonly trainer_type: string;
  readonly trainer_sight_or_berry_tree_id: string;
  readonly script: string;
  readonly flag: string;
}

/** The map.json document. Mirrors the on-disk shape (see PalletTown/map.json). */
export interface MapJson {
  readonly id: string; // MAP_*
  readonly name: string; // directory + map_groups entry
  readonly layout: string; // LAYOUT_*
  readonly music: string;
  readonly region_map_section: string;
  readonly requires_flash: boolean;
  readonly weather: string;
  readonly map_type: string;
  readonly allow_cycling: boolean;
  readonly allow_escaping: boolean;
  readonly allow_running: boolean;
  readonly show_map_name: boolean;
  readonly floor_number: number;
  readonly battle_scene: string;
  readonly connections: ReadonlyArray<MapConnection>;
  readonly object_events: ReadonlyArray<MapObjectEvent>;
  readonly warp_events: ReadonlyArray<MapWarp>;
  readonly coord_events: ReadonlyArray<Record<string, unknown>>;
  readonly bg_events: ReadonlyArray<Record<string, unknown>>;
}

export interface WriteMapResult {
  readonly mapDir: string;
  readonly registeredInGroup: boolean;
  readonly eventScriptIncludeAdded: boolean;
  readonly scriptsStubbed: boolean;
}

export async function writeDecompMap(
  projectRoot: string,
  map: MapJson,
  groupLabel: string,
): Promise<WriteMapResult> {
  const dirRel = `data/maps/${map.name}`;

  // map.json
  await writeFileAtomic(path.join(projectRoot, dirRel, 'map.json'), stringifyDecompJson(map));

  // scripts.inc stub (only if absent - don't clobber authored scripts).
  const scrAbs = path.join(projectRoot, dirRel, 'scripts.inc');
  let scriptsStubbed = false;
  if (!(await fileExists(scrAbs))) {
    await writeFileAtomic(scrAbs, `${map.name}_MapScripts::\n\t.byte 0\n`);
    scriptsStubbed = true;
  }

  // Register in map_groups.json.
  const mgPath = path.join(projectRoot, 'data', 'maps', 'map_groups.json');
  const mg = await readJsonFile<Record<string, unknown>>(mgPath);
  const group = mg[groupLabel];
  if (!Array.isArray(group)) {
    throw new Error(`writeDecompMap: map group '${groupLabel}' not found in map_groups.json`);
  }
  let registeredInGroup = false;
  if (!group.includes(map.name)) {
    group.push(map.name);
    registeredInGroup = true;
  }
  // ALWAYS rewrite (atomic rename bumps mtime) so tools/mapjson regenerates
  // map_groups.h / map_event_ids.h even when only a map.json id/layout changed
  // on a re-author - otherwise a stale generated header keeps a dropped id.
  await writeFileAtomic(mgPath, stringifyDecompJson(mg));

  // Register scripts.inc include in event_scripts.s.
  const eventScriptIncludeAdded = await appendLineIfMissing(
    path.join(projectRoot, 'data', 'event_scripts.s'),
    `\t.include "${dirRel}/scripts.inc"`,
  );

  return { mapDir: dirRel, registeredInGroup, eventScriptIncludeAdded, scriptsStubbed };
}
