export {
  VANILLA_FISHING_SLOT_COUNT,
  VANILLA_LAND_SLOT_COUNT,
  VANILLA_ROCK_SMASH_SLOT_COUNT,
  VANILLA_WATER_SLOT_COUNT,
  WILD_ENCOUNTER_RATE_MAX,
  WILD_POKEMON_INFO_STRUCT_SIZE_BYTES,
  WILD_POKEMON_LEVEL_MAX,
  WILD_POKEMON_SLOT_SIZE_BYTES,
  WILD_POKEMON_SPECIES_MAX,
  parseWildPokemon,
  parseWildPokemonInfo,
  type ParseWildPokemonInfoOptions,
  type WildPokemon,
  type WildPokemonInfo,
  type WildPokemonInfoParseFailure,
  type WildPokemonInfoParseResult,
  type WildPokemonParseFailure,
  type WildPokemonParseResult,
} from './wild-info.js';
